services:
  - type: web
    name: vocaliq
    env: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /blog/how-hummatch-was-built
        destination: /blog/how-hummatch-was-built.html
      - type: rewrite
        source: /blog
        destination: /blog/index.html
      - type: rewrite
        source: /*
        destination: /index.html
